-- MRK Laravel Portal schema for phpMyAdmin on shared hosting.
-- Import this file into the MySQL database created for the site.
CREATE TABLE IF NOT EXISTS migrations (id int unsigned NOT NULL AUTO_INCREMENT, migration varchar(255) NOT NULL, batch int NOT NULL, PRIMARY KEY(id), UNIQUE KEY migrations_migration_unique (migration));
CREATE TABLE IF NOT EXISTS users (id bigint unsigned NOT NULL AUTO_INCREMENT,name varchar(255) NOT NULL,email varchar(255) NOT NULL,password varchar(255) NOT NULL,is_admin tinyint(1) NOT NULL DEFAULT 0,email_verified_at timestamp NULL,remember_token varchar(100) NULL,created_at timestamp NULL,updated_at timestamp NULL,PRIMARY KEY(id),UNIQUE KEY users_email_unique(email));
CREATE TABLE IF NOT EXISTS password_reset_tokens (email varchar(255) NOT NULL,token varchar(255) NOT NULL,created_at timestamp NULL,PRIMARY KEY(email));
CREATE TABLE IF NOT EXISTS sessions (id varchar(255) NOT NULL,user_id bigint unsigned NULL,ip_address varchar(45) NULL,user_agent text NULL,payload longtext NOT NULL,last_activity int NOT NULL,PRIMARY KEY(id),KEY sessions_user_id_index(user_id),KEY sessions_last_activity_index(last_activity));
CREATE TABLE IF NOT EXISTS cache (key varchar(255) NOT NULL,value mediumtext NOT NULL,expiration int NOT NULL,PRIMARY KEY(key));
CREATE TABLE IF NOT EXISTS cache_locks (key varchar(255) NOT NULL,owner varchar(255) NOT NULL,expiration int NOT NULL,PRIMARY KEY(key));
CREATE TABLE IF NOT EXISTS jobs (id bigint unsigned NOT NULL AUTO_INCREMENT,queue varchar(255) NOT NULL,payload longtext NOT NULL,attempts tinyint unsigned NOT NULL,reserved_at int unsigned NULL,available_at int unsigned NOT NULL,created_at int unsigned NOT NULL,PRIMARY KEY(id),KEY jobs_queue_index(queue));
CREATE TABLE IF NOT EXISTS job_batches (id varchar(255) NOT NULL,name varchar(255) NOT NULL,total_jobs int NOT NULL,pending_jobs int NOT NULL,failed_jobs int NOT NULL,failed_job_ids longtext NOT NULL,options mediumtext NULL,cancelled_at int NULL,created_at int NOT NULL,finished_at int NULL,PRIMARY KEY(id));
CREATE TABLE IF NOT EXISTS failed_jobs (id bigint unsigned NOT NULL AUTO_INCREMENT,uuid varchar(255) NOT NULL,connection text NOT NULL,queue text NOT NULL,payload longtext NOT NULL,exception longtext NOT NULL,failed_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,PRIMARY KEY(id),UNIQUE KEY failed_jobs_uuid_unique(uuid));
CREATE TABLE IF NOT EXISTS leads (id bigint unsigned NOT NULL AUTO_INCREMENT,name varchar(100) NOT NULL,email varchar(255) NULL,phone varchar(30) NULL,project_type varchar(80) NOT NULL,message text NOT NULL,status varchar(30) NOT NULL DEFAULT 'new',created_at timestamp NULL,updated_at timestamp NULL,PRIMARY KEY(id),KEY leads_status_index(status));
INSERT INTO migrations (migration,batch) VALUES ('0001_01_01_000000_create_users_table',1),('0001_01_01_000001_create_cache_table',1),('0001_01_01_000002_create_jobs_table',1),('2026_10_08_000003_create_leads_table',1),('2026_10_08_000004_add_is_admin_to_users_table',1);
