@extends('layouts.app') @section('title','Invoice | MRK Digital') @section('robots','noindex,nofollow') @section('content')
<div class="section narrow"><div class="section-heading"><div><span class="eyebrow">INVOICE</span><h1>{{ $mode==='create'?'Create':'Edit' }} Invoice</h1></div><a class="button secondary" href="{{ route('admin.invoices.index') }}">Back</a></div>
<form class="card form-grid" method="post" action="{{ $mode==='create'?route('admin.invoices.store'):route('admin.invoices.update',$invoice) }}">@csrf @if($mode==='edit') @method('PUT') @endif
<label>Customer<select name="customer_id"><option value="">—</option>@foreach($customers as $c)<option value="{{ $c->id }}" @selected(old('customer_id',$invoice->customer_id)==$c->id)>{{ $c->name }}</option>@endforeach</select></label>
<label>Project<select name="project_id"><option value="">—</option>@foreach($projects as $p)<option value="{{ $p->id }}" @selected(old('project_id',$invoice->project_id)==$p->id)>{{ $p->title }}</option>@endforeach</select></label>
<label class="full">Title<input name="title" required value="{{ old('title',$invoice->title) }}"></label>
<label>Discount<input type="number" step="0.01" min="0" name="discount" value="{{ old('discount',$invoice->discount) }}"></label><label>Tax<input type="number" step="0.01" min="0" name="tax" value="{{ old('tax',$invoice->tax) }}"></label>
<label>Paid<input type="number" step="0.01" min="0" name="paid" value="{{ old('paid',$invoice->paid) }}"></label><label>Due date<input type="date" name="due_date" value="{{ old('due_date',$invoice->due_date?->format('Y-m-d')) }}"></label>
<label>Status<select name="status">@foreach(['unpaid','partial','paid','overdue','cancelled'] as $v)<option value="{{ $v }}" @selected(old('status',$invoice->status)===$v)>{{ ucfirst($v) }}</option>@endforeach</select></label>
<label class="full">Item name<textarea name="item_name[]" rows="1" required>{{ old('item_name.0',$invoice->items[0]['name']??'') }}</textarea><input name="item_qty[]" type="number" step="0.01" min="0" value="{{ old('item_qty.0',$invoice->items[0]['qty']??1) }}"><input name="item_price[]" type="number" step="0.01" min="0" value="{{ old('item_price.0',$invoice->items[0]['price']??0) }}"></label>
<label class="full">Notes<textarea name="notes" rows="5">{{ old('notes',$invoice->notes) }}</textarea></label><div class="full"><button class="button primary">Save Invoice</button></div></form></div>@endsection