@extends('layouts.app') @section('title','Quotation | MRK Digital') @section('robots','noindex,nofollow') @section('content')
<div class="section narrow"><div class="section-heading"><div><span class="eyebrow">QUOTATION</span><h1>{{ $mode==='create'?'Create':'Edit' }} Quotation</h1></div><a class="button secondary" href="{{ route('admin.quotes.index') }}">Back</a></div>
<form class="card form-grid" method="post" action="{{ $mode==='create'?route('admin.quotes.store'):route('admin.quotes.update',$quote) }}">@csrf @if($mode==='edit') @method('PUT') @endif
<label>Customer<select name="customer_id"><option value="">—</option>@foreach($customers as $c)<option value="{{ $c->id }}" @selected(old('customer_id',$quote->customer_id)==$c->id)>{{ $c->name }}</option>@endforeach</select></label>
<label>Project<select name="project_id"><option value="">—</option>@foreach($projects as $p)<option value="{{ $p->id }}" @selected(old('project_id',$quote->project_id)==$p->id)>{{ $p->title }}</option>@endforeach</select></label>
<label class="full">Title<input name="title" required value="{{ old('title',$quote->title) }}"></label>
<label>Discount<input type="number" step="0.01" min="0" name="discount" value="{{ old('discount',$quote->discount) }}"></label><label>Tax<input type="number" step="0.01" min="0" name="tax" value="{{ old('tax',$quote->tax) }}"></label>
<label>Status<select name="status">@foreach(['draft','sent','accepted','rejected','expired'] as $v)<option value="{{ $v }}" @selected(old('status',$quote->status)===$v)>{{ ucfirst($v) }}</option>@endforeach</select></label>
<label>Valid until<input type="date" name="valid_until" value="{{ old('valid_until',$quote->valid_until?->format('Y-m-d')) }}"></label>
<label class="full">Items <small>Enter one item per row.</small><textarea name="item_name[]" rows="1" placeholder="Website development">{{ old('item_name.0',$quote->items[0]['name']??'') }}</textarea><input name="item_qty[]" type="number" step="0.01" min="0" value="{{ old('item_qty.0',$quote->items[0]['qty']??1) }}"><input name="item_price[]" type="number" step="0.01" min="0" value="{{ old('item_price.0',$quote->items[0]['price']??0) }}"></label>
<label class="full">Notes<textarea name="notes" rows="5">{{ old('notes',$quote->notes) }}</textarea></label><div class="full"><button class="button primary">Save Quotation</button></div></form></div>@endsection